/* Generated by Together */


/**
 *  Pre-requered :
 *		- mail.jar
 * 		- activation.jar
 */
package com.project.util.mail;  

import java.net.*;
import java.util.*;

import javax.mail.*;
import javax.mail.internet.*;

public class MailSenderModif
{
    private String smtpHost = "";

    private String fromMail = "";
    private String fromName = "";

    private String to = "";

    private String subject = "";
    private String message = "";

    public MailSenderModif() { }

    public void setSMTPHost(String host)  { smtpHost = host;  }
    public void setSenderAddr(String snd)   { fromMail = snd;  }
    public void setSender(String snd)   { fromName = snd;  }

    public void setReceiver(String rcv) { to = rcv;  }

    public void setSubject(String sub)  { subject = sub;  }
    public void setMessage(String msg)  { message = msg;  }

    public void sendMail() throws Exception
    {

       	Properties properties = System.getProperties();
        properties.put("mail.smtp.host", smtpHost);        
        Session ses = Session.getInstance(properties, null);

        MimeMessage mmsg = new MimeMessage(ses);

        // create address fromName
        Address fromAddr = null;
        if(fromMail == null || fromMail.length() == 0) {
            fromAddr = new InternetAddress(fromName);
        }else{
            fromAddr = new InternetAddress(fromMail, fromName);
        }
        mmsg.setFrom(fromAddr);


        // create address to
        Address toAddr = new InternetAddress(to);
        mmsg.setRecipient(Message.RecipientType.TO,toAddr);

        mmsg.setSubject(subject);
        mmsg.setText(message);
        //Transport.send(mmsg);
        
        //hamish
        Transport tr = ses.getTransport("smtp") ;
        tr.connect( "smtp.gmail.com", "oxysystemdanaco@gmail.com", "kosong3kali1" ) ;        
        mmsg.saveChanges() ;
        tr.sendMessage( mmsg, mmsg.getAllRecipients() ) ;
        tr.close() ;


    }

} // end of MailSender
