/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.ccs.session;

import com.project.main.db.CONHandler;
import com.project.main.db.CONResultSet;
import com.project.util.JSPFormater;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Vector;

/**
 *
 * @author Roy
 */
public class SessCOGS {

    public static Vector getCOGS(long locationId, Date start, Date end,String whereGroup) {

        CONResultSet dbrs = null;
        Vector result = new Vector();
        
        if(whereGroup == null || whereGroup.length() <= 0){
            whereGroup = "0";
        }
        
        String grp = " and m.item_group_id in (" + whereGroup + ")";
        String grp2 = " m.item_group_id in (" + whereGroup + ")";
        
        try {
            String sql = "select item_master_id,code,name,round(sum(sales_qty),2) as nsales_qty,round(sum(sales_cogs),2) as nsales_cogs,round(sum(transfer_qty),2) as ntransfer_qty,round(sum(transfer_cogs),2) as ntransfer_cogs,round(sum(transfer_out_qty),2) as ntransfer_out_qty,round(sum(transfer_out_cogs),2) as ntransfer_out_cogs,round(sum(adj_qty),2) as nadj_qty,round(sum(adj_cogs),2) as nadj_cogs,round(sum(incoming_qty),2) as nincoming_qty,round(sum(incoming_cogs),2) as nincoming_cogs,round(sum(retur_qty),2) as nretur_qty,round(sum(retur_cogs),2) as nretur_cogs,round(sum(p_cost_qty),2) as pncost_qty,round(sum(p_cost_cogs),2) as pncost_cogs, " +
                    "round(sum(p_sales_qty),2) as pnsales_qty,round(sum(p_sales_cogs),2) as pnsales_cogs,round(sum(p_transfer_qty),2) as pntransfer_qty,round(sum(p_transfer_cogs),2) as pntransfer_cogs,round(sum(p_transfer_out_qty),2) as pntransfer_out_qty,round(sum(p_transfer_out_cogs),2) as pntransfer_out_cogs,round(sum(p_adj_qty),2) as pnadj_qty,round(sum(p_adj_cogs),2) as pnadj_cogs,round(sum(p_incoming_qty),2) as pnincoming_qty,round(sum(p_incoming_cogs),2) as pnincoming_cogs,round(sum(p_retur_qty),2) as pnretur_qty,round(sum(p_retur_cogs),2) as pnretur_cogs,round(sum(cost_qty),2) as ncost_qty,round(sum(cost_cogs),2) as ncost_cogs, " +
                    "round(sum(p_repackin_qty),2) as pn_repackin_qty,round(sum(p_repackin_cogs),2) as pn_repackin_cogs,round(sum(p_repackout_qty),2) as pn_repackout_qty,round(sum(p_repackout_cogs),2) as pn_repackout_cogs,round(sum(repackin_qty),2) as nrepackin_qty,round(sum(repackin_cogs),2) as nrepackin_cogs,round(sum(repackout_qty),2) as nrepackout_qty,round(sum(repackout_cogs),2) as nrepackout_cogs, "+
                    "round(sum(cogs_qty),2) as n_cogs_qty,round(sum(cogs_total),2) as n_cogs_total, round(sum(precadj_qty),2) as nprecadj_qty,round(sum(precadj_cogs),2) as nprecadj_cogs,round(sum(recadj_qty),2) as nrecadj_qty,round(sum(recadj_cogs),2) as nrecadj_cogs "+                                        
                    " from ( " +
                    
                    //=============Previous======================
                    //sales
                    "select m.item_master_id,m.code,m.name,sum(sd.qty) as p_sales_qty,sum(sd.qty * sd.cogs) as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_sales s inner join pos_sales_detail sd on s.sales_id = sd.sales_id inner join pos_item_master m on sd.product_master_id = m.item_master_id where s.location_id = " + locationId + " "+grp+" and s.date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and s.type in (0,1) group by m.item_master_id union " +                    
                    "select m.item_master_id,m.code,m.name,sum(sd.qty * -1) as p_sales_qty,sum(sd.qty * sd.cogs * -1) as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_sales s inner join pos_sales_detail sd on s.sales_id = sd.sales_id inner join pos_item_master m on sd.product_master_id = m.item_master_id where s.location_id =  " + locationId +" "+grp+" and s.date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and s.type in (2,3) group by m.item_master_id union " +
                    //transfer
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,sum(ti.qty) as p_transfer_qty,sum(ti.qty * ti.price) as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs,0 as transfer_qty,0 as p_transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_transfer t inner join pos_transfer_item ti on t.transfer_id = ti.transfer_id inner join pos_item_master m on ti.item_master_id = m.item_master_id  where t.status = 'APPROVED' "+grp+" and t.approval_1_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and t.to_location_id = " + locationId + " group by m.item_master_id union " +
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,sum(ti.qty) as p_transfer_out_qty,sum(ti.qty * ti.price) as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs,0 as transfer_qty,0 as transfer_cogs,0 as transfer_out_qty, 0 as p_transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_transfer t inner join pos_transfer_item ti on t.transfer_id = ti.transfer_id inner join pos_item_master m on ti.item_master_id = m.item_master_id  where t.status = 'APPROVED' "+grp+" and t.approval_1_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and t.from_location_id = " + locationId + " group by m.item_master_id union " +
                    
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,sum(ti.qty_balance) as p_adj_qty,sum(ti.qty_balance * ti.price) as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs, 0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_adjusment t inner join pos_adjusment_item ti on t.adjusment_id = ti.adjusment_id inner join pos_item_master m on ti.item_master_id = m.item_master_id where t.status in ('APPROVED','POSTED') "+grp+" and t.approval_1_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and t.location_id = " + locationId + " group by m.item_master_id union " +
                    
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,sum(qty) as p_incoming_qty,sum(round(total_amount - (discount_percent*total_amount/100),2)) as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from (select r.receive_id,round(r.discount_total/sum(ri.total_amount)*100,2) as discount_percent from ((select r.* from pos_receive r inner join pos_receive_item ri on r.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where r.type_ap = 0 and r.status in ('APPROVED','CHECKED') and r.approval_1_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and r.location_id = " + locationId + " "+grp+" group by r.receive_id )) r inner join pos_receive_item ri on r.receive_id = ri.receive_id where r.type_ap = 0 and r.status in ('APPROVED','CHECKED') and r.approval_1_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and r.location_id = " + locationId + " group by r.receive_id) rc inner join pos_receive_item ri on rc.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by ri.item_master_id union "+
                    
                    //Rec Adj
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,sum(round(total_amount - (discount_percent*total_amount/100),2)) as precadj_cogs,0 as recadj_qty,0 as recadj_cogs  from (select r.receive_id,round(r.discount_total/sum(ri.total_amount)*100,2) as discount_percent from ((select r.* from pos_receive r inner join pos_receive_item ri on r.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where r.type_ap = 4 and r.status in ('APPROVED','CHECKED') and r.approval_1_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and r.location_id = " + locationId + " "+grp+" group by r.receive_id )) r inner join pos_receive_item ri on r.receive_id = ri.receive_id where r.type_ap = 4 and r.status in ('APPROVED','CHECKED') and r.approval_1_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and r.location_id = " + locationId + " group by r.receive_id) rc inner join pos_receive_item ri on rc.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by ri.item_master_id union "+
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,sum(qty) as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs  from (select r.receive_id,round(r.discount_total/sum(ri.total_amount)*100,2) as discount_percent from ((select r.* from pos_receive r inner join pos_receive_item ri on r.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where r.type_ap = 3 and r.status in ('APPROVED','CHECKED') and r.approval_1_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and r.location_id = " + locationId + " "+grp+" group by r.receive_id )) r inner join pos_receive_item ri on r.receive_id = ri.receive_id where r.type_ap = 4 and r.status in ('APPROVED','CHECKED') and r.approval_1_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and r.location_id = " + locationId + " group by r.receive_id) rc inner join pos_receive_item ri on rc.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by ri.item_master_id union "+
                    //--- end rec adj---
                    
                    //Retur
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,sum(ri.qty) as p_retur_qty,sum(ri.total_amount - ( ri.total_amount/r.total * r.discount_total )) as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0 as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from (select r.retur_id,r.number,sum(ri.total_amount) as total,r.discount_total as discount_total from pos_retur r inner join pos_retur_item ri on r.retur_id = ri.retur_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where (r.status ='APPROVED' or r.status ='POSTED') "+grp+" and r.location_id = " + locationId + " and approval_1_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') group by r.retur_id) r inner join pos_retur_item ri on r.retur_id = ri.retur_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by m.item_master_id union "+
                    
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,sum(ti.qty) as p_cost_qty,sum(ti.qty * ti.price) as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_costing t inner join pos_costing_item ti on t.costing_id = ti.costing_id inner join pos_item_master m on ti.item_master_id = m.item_master_id where t.status in ('APPROVED','POSTED') "+grp+" and t.effective_date < ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and t.location_id = " + locationId + " group by m.item_master_id union " +
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,sum(ri.qty) as p_repackin_qty,sum(ri.qty*ri.cogs) as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_repack r inner join pos_repack_item ri on r.repack_id = ri.repack_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where ri.type = 1 and r.location_id = " + locationId+" and to_days(r.effective_date) < to_days('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + "') and r.status in ('APPROVED','POSTED') " + grp + " group by m.item_master_id union " +
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,sum(ri.qty) as p_repackout_qty,sum(ri.qty*ri.cogs) as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_repack r inner join pos_repack_item ri on r.repack_id = ri.repack_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where ri.type = 0 and r.location_id = " + locationId+" and to_days(r.effective_date) < to_days('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + "') and r.status in ('APPROVED','POSTED') " + grp + " group by m.item_master_id union " +
                    
                    //cogs
                    " select item_id as item_master_id,code as code,name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,sum(qty) as cogs_qty,sum(cogs) as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs "+
                    " from ( "+
                    " (select m.item_master_id as item_id,m.code as code,typex,m.name as name,sum(qty) as qty,sum(round(total_amount - (discount_percent*total_amount/100),2)) as cogs from "+
                    " (select r.receive_id,r.type as typex,round(r.discount_total/sum(ri.total_amount)*100,2) as discount_percent from "+
                    " ((select r.* from pos_receive r inner join pos_receive_item ri on r.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where r.type_ap in (0) and r.status in ('APPROVED','CHECKED') and r.approval_1_date <= ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') "+grp+" group by r.receive_id )) r "+
                    " inner join pos_receive_item ri on r.receive_id = ri.receive_id where r.type_ap in (0) and r.status in ('APPROVED','CHECKED') and r.approval_1_date <= ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') group by r.receive_id) rc inner join pos_receive_item ri on rc.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by ri.item_master_id) "+
                    " union "+
                    " (select m.item_master_id as item_id,m.code as code,typex,m.name,0 as qty,sum(round(total_amount - (discount_percent*total_amount/100),2)) as cogs from "+
                    " (select r.receive_id,r.type as typex,round(r.discount_total/sum(ri.total_amount)*100,2) as discount_percent from "+
                    " ((select r.* from pos_receive r inner join pos_receive_item ri on r.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where r.type_ap in (4) and r.status in ('APPROVED','CHECKED') and r.approval_1_date <= ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') "+grp+" group by r.receive_id )) r "+
                    " inner join pos_receive_item ri on r.receive_id = ri.receive_id where r.type_ap in (4) and r.status in ('APPROVED','CHECKED') and r.approval_1_date <= ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') group by r.receive_id) rc inner join pos_receive_item ri on rc.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by ri.item_master_id ) " +
                    " union "+
                    " (select m.item_master_id as item_id,m.code as code,typex,m.name,sum(qty) as qty,0 as cogs from "+
                    " (select r.receive_id,r.type as typex,round(r.discount_total/sum(ri.total_amount)*100,2) as discount_percent from "+
                    " ((select r.* from pos_receive r inner join pos_receive_item ri on r.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where r.type_ap in (3) and r.status in ('APPROVED','CHECKED') and r.approval_1_date <= ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') "+grp+" group by r.receive_id )) r "+
                    " inner join pos_receive_item ri on r.receive_id = ri.receive_id where r.type_ap in (3) and r.status in ('APPROVED','CHECKED') and r.approval_1_date <= ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') group by r.receive_id) rc inner join pos_receive_item ri on rc.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by ri.item_master_id ) " +                    
                    " ) as x group by item_id union "+
                    
                    
                    
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,sum(sd.qty) as sales_qty,sum(sd.qty * sd.cogs) as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_sales s inner join pos_sales_detail sd on s.sales_id = sd.sales_id inner join pos_item_master m on sd.product_master_id = m.item_master_id where s.location_id = " + locationId + " "+grp+" and s.date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and s.type in (0,1) group by m.item_master_id union " +
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,sum(sd.qty * -1) as sales_qty,sum(sd.qty * sd.cogs * -1) as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_sales s inner join pos_sales_detail sd on s.sales_id = sd.sales_id inner join pos_item_master m on sd.product_master_id = m.item_master_id where s.location_id =  " + locationId +" "+grp+" and s.date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and s.type in (2,3) group by m.item_master_id union " +
                    
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, sum(ti.qty) as transfer_qty,sum(ti.qty * ti.price) as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_transfer t inner join pos_transfer_item ti on t.transfer_id = ti.transfer_id inner join pos_item_master m on ti.item_master_id = m.item_master_id  where t.status = 'APPROVED' "+grp+" and t.approval_1_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and t.to_location_id = " + locationId + " group by m.item_master_id union " +
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, sum(ti.qty) as transfer_out_qty, sum(ti.qty * ti.price) as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_transfer t inner join pos_transfer_item ti on t.transfer_id = ti.transfer_id inner join pos_item_master m on ti.item_master_id = m.item_master_id  where t.status = 'APPROVED' "+grp+" and t.approval_1_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and t.from_location_id = " + locationId + " group by m.item_master_id union " +
                    
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,sum(ti.qty_balance) as adj_qty,sum(ti.qty_balance * ti.price) as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_adjusment t inner join pos_adjusment_item ti on t.adjusment_id = ti.adjusment_id inner join pos_item_master m on ti.item_master_id = m.item_master_id where t.status in ('APPROVED','POSTED') "+grp+" and t.approval_1_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and t.location_id = " + locationId + " group by m.item_master_id union " +
                    
                    
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,sum(qty) as incoming_qty,sum(round(total_amount - (discount_percent*total_amount/100),2)) as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from (select r.receive_id,round(r.discount_total/sum(ri.total_amount)*100,2) as discount_percent from ((select r.* from pos_receive r inner join pos_receive_item ri on r.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where r.type_ap = 0 and r.status in ('APPROVED','CHECKED') and r.approval_1_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and r.location_id = " + locationId + " "+grp+" group by r.receive_id )) r inner join pos_receive_item ri on r.receive_id = ri.receive_id where r.type_ap = 0 and r.status in ('APPROVED','CHECKED') and r.approval_1_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and r.location_id = " + locationId + " group by r.receive_id) rc inner join pos_receive_item ri on rc.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by ri.item_master_id union "+
                    
                    //Rec Adj
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,sum(round(total_amount - (discount_percent*total_amount/100),2)) as recadj_cogs from (select r.receive_id,round(r.discount_total/sum(ri.total_amount)*100,2) as discount_percent from ((select r.* from pos_receive r inner join pos_receive_item ri on r.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where r.type_ap = 4 and r.status in ('APPROVED','CHECKED') and r.approval_1_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and r.location_id = " + locationId + " "+grp+" group by r.receive_id )) r inner join pos_receive_item ri on r.receive_id = ri.receive_id where r.type_ap = 4 and r.status in ('APPROVED','CHECKED') and r.approval_1_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and r.location_id = " + locationId + " group by r.receive_id) rc inner join pos_receive_item ri on rc.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by ri.item_master_id union "+
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,sum(qty) as recadj_qty,0 as recadj_cogs from (select r.receive_id,round(r.discount_total/sum(ri.total_amount)*100,2) as discount_percent from ((select r.* from pos_receive r inner join pos_receive_item ri on r.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where r.type_ap = 3 and r.status in ('APPROVED','CHECKED') and r.approval_1_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and r.location_id = " + locationId + " "+grp+" group by r.receive_id )) r inner join pos_receive_item ri on r.receive_id = ri.receive_id where r.type_ap = 4 and r.status in ('APPROVED','CHECKED') and r.approval_1_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and r.location_id = " + locationId + " group by r.receive_id) rc inner join pos_receive_item ri on rc.receive_id = ri.receive_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by ri.item_master_id union "+
                    //--- end rec adj
                    
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,sum(ri.qty) as retur_qty,sum(ri.total_amount - ( ri.total_amount/r.total * r.discount_total )) as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from (select r.retur_id,r.number,sum(ri.total_amount) as total,r.discount_total as discount_total from pos_retur r inner join pos_retur_item ri on r.retur_id = ri.retur_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where (r.status ='APPROVED' or r.status ='POSTED') "+grp+" and r.location_id = " + locationId + " and approval_1_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') group by r.retur_id) r inner join pos_retur_item ri on r.retur_id = ri.retur_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where "+grp2+" group by m.item_master_id union "+                    
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,sum(ti.qty) as cost_qty,sum(ti.qty * ti.price) as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_costing t inner join pos_costing_item ti on t.costing_id = ti.costing_id inner join pos_item_master m on ti.item_master_id = m.item_master_id where t.status in ('APPROVED','POSTED') "+grp+" and t.effective_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and t.location_id = " + locationId + " group by m.item_master_id union " +
                    
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,sum(ri.qty) as repackin_qty,sum(ri.qty*ri.cogs) as repackin_cogs,0 as repackout_qty,0 as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_repack r inner join pos_repack_item ri on r.repack_id = ri.repack_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where ri.type = 1 and r.location_id = " + locationId+" and r.effective_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and r.status in ('APPROVED','POSTED') " + grp + " group by m.item_master_id union " +
                    "select m.item_master_id,m.code,m.name,0 as p_sales_qty,0 as p_sales_cogs,0 as p_transfer_qty,0 as p_transfer_cogs,0 as p_transfer_out_qty,0 as p_transfer_out_cogs,0 as p_adj_qty,0 as p_adj_cogs,0 as p_incoming_qty,0 as p_incoming_cogs,0 as p_retur_qty,0 as p_retur_cogs,0 as p_cost_qty,0 as p_cost_cogs,0 as sales_qty,0 as sales_cogs, 0 as transfer_qty,0 as transfer_cogs, 0 as transfer_out_qty, 0 as transfer_out_cogs,0 as adj_qty,0 as adj_cogs,0 as incoming_qty,0 as incoming_cogs,0 as retur_qty,0  as retur_cogs,0 as cost_qty,0 as cost_cogs,0 as p_repackin_qty,0 as p_repackin_cogs,0 as p_repackout_qty,0 as p_repackout_cogs,0 as repackin_qty,0 as repackin_cogs,sum(ri.qty) as repackout_qty,sum(ri.qty*ri.cogs) as repackout_cogs,0 as cogs_qty,0 as cogs_total,0 as precadj_qty,0 as precadj_cogs,0 as recadj_qty,0 as recadj_cogs from pos_repack r inner join pos_repack_item ri on r.repack_id = ri.repack_id inner join pos_item_master m on ri.item_master_id = m.item_master_id where ri.type = 0 and r.location_id = " + locationId+" and r.effective_date between ('" + JSPFormater.formatDate(start, "yyyy-MM-dd") + " 00:00:00') and ('" + JSPFormater.formatDate(end, "yyyy-MM-dd") + " 23:59:59') and r.status in ('APPROVED','POSTED') " + grp + " group by m.item_master_id " +
                    " ) as x group by item_master_id order by name ";
            
            dbrs = CONHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();

            while (rs.next()) {
                Vector tmp = new Vector();
                tmp.add("" + rs.getLong("item_master_id"));
                tmp.add("" + rs.getString("code"));
                tmp.add("" + rs.getString("name"));
                tmp.add("" + rs.getDouble("nsales_qty"));
                tmp.add("" + rs.getDouble("nsales_cogs"));
                tmp.add("" + rs.getDouble("ntransfer_qty"));
                tmp.add("" + rs.getDouble("ntransfer_cogs"));
                tmp.add("" + rs.getDouble("ntransfer_out_qty"));
                tmp.add("" + rs.getDouble("ntransfer_out_cogs"));
                tmp.add("" + rs.getDouble("nadj_qty"));
                tmp.add("" + rs.getDouble("nadj_cogs"));
                tmp.add("" + rs.getDouble("nincoming_qty"));
                tmp.add("" + rs.getDouble("nincoming_cogs"));                
                tmp.add("" + rs.getDouble("nretur_qty"));
                tmp.add("" + rs.getDouble("nretur_cogs"));
                
                tmp.add("" + rs.getDouble("pnsales_qty"));
                tmp.add("" + rs.getDouble("pnsales_cogs"));
                tmp.add("" + rs.getDouble("pntransfer_qty"));
                tmp.add("" + rs.getDouble("pntransfer_cogs"));
                tmp.add("" + rs.getDouble("pntransfer_out_qty"));
                tmp.add("" + rs.getDouble("pntransfer_out_cogs"));
                tmp.add("" + rs.getDouble("pnadj_qty"));
                tmp.add("" + rs.getDouble("pnadj_cogs"));
                tmp.add("" + rs.getDouble("pnincoming_qty"));
                tmp.add("" + rs.getDouble("pnincoming_cogs"));                
                tmp.add("" + rs.getDouble("pnretur_qty"));
                tmp.add("" + rs.getDouble("pnretur_cogs"));
                
                tmp.add("" + rs.getDouble("pncost_qty"));
                tmp.add("" + rs.getDouble("pncost_cogs"));
                
                tmp.add("" + rs.getDouble("ncost_qty"));
                tmp.add("" + rs.getDouble("ncost_cogs"));
                
                tmp.add("" + rs.getDouble("pn_repackin_qty"));
                tmp.add("" + rs.getDouble("pn_repackin_cogs"));
                tmp.add("" + rs.getDouble("pn_repackout_qty"));
                tmp.add("" + rs.getDouble("pn_repackout_cogs"));
                
                tmp.add("" + rs.getDouble("nrepackin_qty"));
                tmp.add("" + rs.getDouble("nrepackin_cogs"));
                
                tmp.add("" + rs.getDouble("nrepackout_qty"));
                tmp.add("" + rs.getDouble("nrepackout_cogs"));
                
                //=====================================
                tmp.add("" + rs.getDouble("n_cogs_qty"));
                tmp.add("" + rs.getDouble("n_cogs_total"));
                
                tmp.add("" + rs.getDouble("nprecadj_qty"));
                tmp.add("" + rs.getDouble("nprecadj_cogs"));
                
                tmp.add("" + rs.getDouble("nrecadj_qty"));
                tmp.add("" + rs.getDouble("nrecadj_cogs"));

                result.add(tmp);

            }

        } catch (Exception e) {
            System.out.println("[exception] " + e.toString());
        } finally {
            CONResultSet.close(dbrs);
        }

        return result;
    }
    
    //amount cogs by vendor
    public static double getCOGSByVendor(long itemId){
        CONResultSet dbrs = null;
        double cogs = 0;
        try{
            String sql = "select round(sum(last_price)/count(*),2) as cogs from pos_vendor_item where item_master_id = "+itemId;
            
            dbrs = CONHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();
            
            while(rs.next()){
                cogs = rs.getDouble("cogs");
            }
        } catch (Exception e) {
            System.out.println("[exception] " + e.toString());
        } finally {
            CONResultSet.close(dbrs);
        }
        
        return cogs;
        
    }
    
    public static double getCOGSByItem(long itemId){
        CONResultSet dbrs = null;
        double cogs = 0;
        try{
            String sql = "select cogs as cogs from pos_item_master where item_master_id = "+itemId;
            
            dbrs = CONHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();
            
            while(rs.next()){
                cogs = rs.getDouble("cogs");
            }
        } catch (Exception e) {
            System.out.println("[exception] " + e.toString());
        } finally {
            CONResultSet.close(dbrs);
        }
        
        return cogs;
        
    }
    
}
